/**
 * Generated by rsql-types from tests/typecheck/books.schema.json. Do not edit: regenerate it instead.
 *
 * Every operation the schema declares, with what it takes and what a row of
 * its answer is. `row` is `Record<string, unknown>` wherever the schema does
 * not describe the document — which is everywhere but a read with a declared
 * projection, because this store does not impose a shape on documents. That
 * is the schema's true answer, not a gap waiting to be filled.
 */

export interface Books {
  /** `scan` on `books`. */
  "books.on_shelf": {
    args: {
      shelf: string;
      since?: number;
    };
    /**
     * The projected fields. Each is optional: the store keeps only those the
     * document had. Each is `unknown`: the schema names the fields, never
     * their types. The key is the declared path verbatim, not a nested path.
     */
    row: {
      title?: unknown;
      shelf?: unknown;
      "author.name"?: unknown;
    };
  };

  /** `count` on `books`. */
  "books.how_many": {
    args: {};
    /** A count sends back no rows; `key`, `changed` and `count` are its answer. */
    row: never;
  };
}

/** Every operation name the schema declares. */
export type BooksOperation = keyof Books;
