/**
 * Generated by rsql-types from tests/typecheck/coverage.schema.json. Do not edit: regenerate it instead.
 *
 * Every operation the schema declares, with what it takes and what a row of
 * its answer is. `row` is `Record<string, unknown>` wherever the schema does
 * not describe the document — which is everywhere but a read with a declared
 * projection, because this store does not impose a shape on documents. That
 * is the schema's true answer, not a gap waiting to be filled.
 */

export interface Coverage {
  /** `insert` on `items`. */
  "items.add": {
    args: {
      id: string;
      kind: string;
      at: number;
      amount: number;
      flag?: boolean;
      extra?: unknown;
      label?: string;
    };
    /** An insert sends back no rows; `key`, `changed` and `count` are its answer. */
    row: never;
  };

  /** `get` on `items`. */
  "items.detail": {
    args: {
      id: string;
    };
    /**
     * The projected fields. Each is optional: the store keeps only those the
     * document had. Each is `unknown`: the schema names the fields, never
     * their types. The key is the declared path verbatim, not a nested path.
     */
    row: {
      kind?: unknown;
      "nested.deep"?: unknown;
    };
  };

  /** `scan` on `items`. */
  "items.of_kind": {
    args: {
      kind: string;
      since?: number;
    };
    /**
     * The projected fields. Each is optional: the store keeps only those the
     * document had. Each is `unknown`: the schema names the fields, never
     * their types. The key is the declared path verbatim, not a nested path.
     */
    row: {
      kind?: unknown;
      amount?: unknown;
    };
  };

  /** `count` on `items`. */
  "items.how_many": {
    args: {};
    /** A count sends back no rows; `key`, `changed` and `count` are its answer. */
    row: never;
  };

  /** `totals` on `items`. */
  "items.per_kind": {
    args: {
      kind?: string;
    };
    /** A rollup row: a count, the group values, and one field per declared total. The rollup says which; this does not read it. */
    row: Record<string, unknown>;
  };

  /** `put` on `items`. */
  "items.replace": {
    args: {
      id: string;
      kind: string;
      at: number;
      amount: number;
    };
    /** A put sends back no rows; `key`, `changed` and `count` are its answer. */
    row: never;
  };

  /** `update` on `items`. */
  "items.retag": {
    args: {
      id: string;
      kind: string;
    };
    /** An update sends back no rows; `key`, `changed` and `count` are its answer. */
    row: never;
  };

  /** `delete` on `items`. */
  "items.drop": {
    args: {
      id: string;
    };
    /** A delete sends back no rows; `key`, `changed` and `count` are its answer. */
    row: never;
  };

  /** `batch` on `items`. */
  "items.note": {
    args: {
      id: string;
      kind: string;
      body: string;
    };
    /** A batch sends back no rows; `key`, `changed` and `count` are its answer. */
    row: never;
  };
}

/** Every operation name the schema declares. */
export type CoverageOperation = keyof Coverage;
