/**
 * Generated by rsql-types from fixtures/ledger.schema.json. Do not edit: regenerate it instead.
 *
 * Every operation the schema declares, with what it takes and what a row of
 * its answer is. `row` is `Record<string, unknown>` wherever the schema does
 * not describe the document — which is everywhere but a read with a declared
 * projection, because this store does not impose a shape on documents. That
 * is the schema's true answer, not a gap waiting to be filled.
 */

export interface Schema {
  /** `insert` on `orders`. */
  "orders.place": {
    args: {
      id: string;
      customer: string;
      total: number;
    };
    /** An insert sends back no rows; `key`, `changed` and `count` are its answer. */
    row: never;
  };

  /** `batch` on `orders`. */
  "orders.pay": {
    args: {
      order: string;
      amount: number;
      at: number;
      reference: string;
    };
    /** A batch sends back no rows; `key`, `changed` and `count` are its answer. */
    row: never;
  };

  /** `get` on `orders`. */
  "orders.get": {
    args: {
      id: string;
    };
    /** The schema does not describe documents, so the shape of this row is genuinely not known here. */
    row: Record<string, unknown>;
  };

  /** `scan` on `payments`. */
  "payments.of_order": {
    args: {
      order: string;
    };
    /** The schema does not describe documents, so the shape of this row is genuinely not known here. */
    row: Record<string, unknown>;
  };

  /** `scan` on `entries`. */
  "entries.of_account": {
    args: {
      account: string;
    };
    /** The schema does not describe documents, so the shape of this row is genuinely not known here. */
    row: Record<string, unknown>;
  };
}

/** Every operation name the schema declares. */
export type SchemaOperation = keyof Schema;
